# Generated by Django 4.2.6 on 2023-12-17 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_material_productmaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ManyToManyField(related_name='materials', through='simpleapp.ProductMaterial', to='simpleapp.material'),
        ),
        migrations.AlterField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='simpleapp.product'),
        ),
    ]
